### ISSUE TITLE
Character Movements

### ISSUE THREAD

**Issue by dehaotu** [ankitagupta820/CSCI526#2]

**Comment by dehaotu** [comment]
- Perfect Character Movement Control (maybe some air resistance or smoothness)
- finite bound for getting started

**Comment by poojadesaidev** [comment]
Resources used :
Git : https://www.youtube.com/watch?v=qpXxcvS-g3g 
Boundaries : https://www.youtube.com/watch?v=ailbszpt_AI&t=5s
Movements : 
https://www.youtube.com/watch?v=fyV77lN1Yl0
https://www.youtube.com/watch?v=NEUzB5vPYrE

Gravity:https://www.youtube.com/watch?v=dbAdLs-NlzI

Infinite Path: https://www.youtube.com/watch?v=HIsEqKPoJXM


Notes :
Boundaries : Player is bounded on two axis only, X and Z. Not on Y, as he is falling in the Y axis.

To Do Later:
Animations to create movable obstacles : https://www.youtube.com/watch?v=fyV77lN1Yl0&t=2603s

Navigations to create glide?? : https://www.youtube.com/watch?v=fyV77lN1Yl0&t=2232s
